# Generated by Django 5.0 on 2024-01-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_playeringame_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='ip_address',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
