# Generated by Django 4.2.7 on 2023-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.PositiveIntegerField(default=True, unique=True)),
                ('player_nick', models.TextField(max_length=200)),
                ('is_win', models.BooleanField(default=False)),
                ('card_1', models.CharField(max_length=20)),
                ('card_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.CharField(max_length=20)),
                ('card_2', models.CharField(max_length=20)),
                ('card_3', models.CharField(max_length=20)),
                ('card_4', models.CharField(max_length=20)),
                ('card_5', models.CharField(max_length=20)),
                ('max_player_num', models.PositiveIntegerField(default=4)),
                ('current_player_num', models.PositiveBigIntegerField(default=0)),
                ('coins', models.PositiveIntegerField()),
            ],
        ),
    ]
